/**
 * @file qmc5883p.h
 * @brief QMC5883P Magnetometer Sensor Driver Library
 * 
 * This library provides an interface to the QMC5883P 3-axis magnetometer sensor.
 * It supports various operation modes, data rates and measurement ranges.
 * The library includes calibration parameters for accurate magnetic field measurements.
 * OSR settings are fixed to 2.
 * 
 * @author WilliTourt willitourt@foxmail.com
 * @version 1.0
 * @date 2025.11.28
 * 
 * @note Comments are mostly generated by AI
 * 
 * @CHANGELOG:
 * - 1.0: Transferred from initial C version to C++ version, added mode configuration
 * 
 */

#pragma once

#include "main.h"

#if !defined(__STM32F1xx_HAL_H) && \
    !defined(__STM32F4xx_HAL_H) && \
    !defined(__STM32F7xx_HAL_H) && \
    !defined(__STM32H7xx_HAL_H) && \
    !defined(__STM32L4xx_HAL_H) && \
    !defined(__STM32G0xx_HAL_H) && \
    !defined(__STM32WBxx_HAL_H) && \
    !defined(__STM32WLxx_HAL_H)
#error "The QMC5883P Library can only be used with STM32Cube HAL drivers"
#endif

#if !defined(HAL_I2C_MODULE_ENABLED)
#error "At least one IIC port should be opened"
#endif

/* QMC5833P User Configuration ******************************************/

// QMC5883P I2C address
#define QMC5883P_ADDR 0x2C  // 0010 1100 << 1

// QMC5883P Chip ID
#define QMC5883P_CHIP_ID 0x80

// QMC5883P Read Timeout (ms)
#define QMC5883P_READ_TIMEOUT_MS 100

// Magnetic calibration parameters
#define MAG_X_OFFSET            0.068928f
#define MAG_Y_OFFSET            0.003696f
#define MAG_Z_OFFSET            0.024412f
#define MAG_X_SCALE             0.977537f
#define MAG_Y_SCALE             1.026078f
#define MAG_Z_SCALE             0.997570f

/* QMC5833P Register Map ************************************************/

// QMC5883P Registers
#define QMC5883P_REG_CHIP_ID       0x00  // Chip ID register
#define QMC5883P_REG_XOUT_L        0x01  // X-axis data LSB
#define QMC5883P_REG_XOUT_H        0x02  // X-axis data MSB
#define QMC5883P_REG_YOUT_L        0x03  // Y-axis data LSB
#define QMC5883P_REG_YOUT_H        0x04  // Y-axis data MSB
#define QMC5883P_REG_ZOUT_L        0x05  // Z-axis data LSB
#define QMC5883P_REG_ZOUT_H        0x06  // Z-axis data MSB
#define QMC5883P_REG_STATUS        0x09  // Status register (OVFL, DRDY)
#define QMC5883P_REG_CONTROL_1     0x0A  // Control register 1 (OSR2, OSR1, ODR, MODE)
#define QMC5883P_REG_CONTROL_2     0x0B  // Control register 2 (SOFT_RST, SELF_TEST, RNG, SET/RESET MODE)


// QMC5883P Status Register Bits
#define QMC5883P_STATUS_DRDY       0x01  // Data Ready
#define QMC5883P_STATUS_OVL        0x02  // Overflow

// QMC5883P Control Register 1 Bits
#define QMC5883P_CONTROL_1_MODE_SUSPEND  0x00  // Suspend mode
#define QMC5883P_CONTROL_1_MODE_NORMAL   0x01  // Normal mode
#define QMC5883P_CONTROL_1_MODE_SINGLE   0x02  // Single mode
#define QMC5883P_CONTROL_1_MODE_CONT     0x03  // Continuous mode

#define QMC5883P_CONTROL_1_OSR1_8        0x00  // Over Sample Rate: 8
#define QMC5883P_CONTROL_1_OSR1_4        0x10  // Over Sample Rate: 4
#define QMC5883P_CONTROL_1_OSR1_2        0x20  // Over Sample Rate: 2
#define QMC5883P_CONTROL_1_OSR1_1        0x30  // Over Sample Rate: 1
#define QMC5883P_CONTROL_1_OSR2_1        0x00  // Down Sample Rate: 1
#define QMC5883P_CONTROL_1_OSR2_2        0x40  // Down Sample Rate: 2
#define QMC5883P_CONTROL_1_OSR2_4        0x80  // Down Sample Rate: 4
#define QMC5883P_CONTROL_1_OSR2_8        0xC0  // Down Sample Rate: 8

// QMC5883P Control Register 2 Bits
#define QMC5883P_CONTROL_2_SOFT_RESET    0x80  // Soft reset
#define QMC5883P_CONTROL_2_SELF_TEST     0x40  // Self test
#define QMC5883P_CONTROL_2_MODE          0x00  // SET/RESET MODE

// QMC5883P RATE
#define QMC5883P_CONTROL_1_ODR_10HZ      0x00  // Output Data Rate: 10Hz
#define QMC5883P_CONTROL_1_ODR_50HZ      0x04  // Output Data Rate: 50Hz
#define QMC5883P_CONTROL_1_ODR_100HZ     0x08  // Output Data Rate: 100Hz
#define QMC5883P_CONTROL_1_ODR_200HZ     0x0C  // Output Data Rate: 200Hz

// QMC5883P RANGE
#define QMC5883P_CONTROL_2_RNG_2G        0x0C  // Range: ±2G
#define QMC5883P_CONTROL_2_RNG_8G        0x08  // Range: ±8G
#define QMC5883P_CONTROL_2_RNG_12G       0x04  // Range: ±12G
#define QMC5883P_CONTROL_2_RNG_30G       0x00  // Range: ±30G

// QMC5883P SENSITIVITY
#define QMC5883_RNG_SENSITIVITY_2G       15000 // LSB/Gauss
#define QMC5883_RNG_SENSITIVITY_8G       3750  // LSB/Gauss
#define QMC5883_RNG_SENSITIVITY_12G      2500  // LSB/Gauss
#define QMC5883_RNG_SENSITIVITY_30G      1000  // LSB/Gauss



/**
 * @class QMC5883P
 * @brief Driver for QMC5883P 3-axis magnetometer sensor
 * 
 * This class provides methods to initialize, configure and read data
 * from the QMC5883P magnetometer sensor. It supports I2C communication and
 * includes built-in calibration parameters.
 */
class QMC5883P {
    public:
        /**
         * @brief Status codes returned by QMC5883P functions
         */
        enum class QMC5883P_Status {
            OK,         ///< Operation successful
            ERROR,      ///< General error occurred
            ERROR_ID    ///< Chip ID verification failed
        };

        /**
         * @brief Operation modes of the QMC5883P sensor
         */
        enum class QMC5883P_Mode {
            SUSPEND = QMC5883P_CONTROL_1_MODE_SUSPEND,   ///< Suspend mode (low power)
            NORMAL = QMC5883P_CONTROL_1_MODE_NORMAL,     ///< Normal mode
            SINGLE = QMC5883P_CONTROL_1_MODE_SINGLE,     ///< Single measurement mode
            CONTINUOUS = QMC5883P_CONTROL_1_MODE_CONT    ///< Continuous measurement mode
        };

        /**
         * @brief Output data rates of the QMC5883P sensor
         */
        enum class QMC5883P_Spd {
            ODR_10HZ = QMC5883P_CONTROL_1_ODR_10HZ,     ///< 10Hz output data rate
            ODR_50HZ = QMC5883P_CONTROL_1_ODR_50HZ,     ///< 50Hz output data rate
            ODR_100HZ = QMC5883P_CONTROL_1_ODR_100HZ,   ///< 100Hz output data rate
            ODR_200HZ = QMC5883P_CONTROL_1_ODR_200HZ    ///< 200Hz output data rate
        };

        /**
         * @brief Measurement ranges of the QMC5883P sensor
         */
        enum class QMC5883P_Rng {
            RNG_2G = QMC5883P_CONTROL_2_RNG_2G,     ///< ±2G measurement range
            RNG_8G = QMC5883P_CONTROL_2_RNG_8G,     ///< ±8G measurement range
            RNG_12G = QMC5883P_CONTROL_2_RNG_12G,   ///< ±12G measurement range
            RNG_30G = QMC5883P_CONTROL_2_RNG_30G    ///< ±30G measurement range
        };

        /**
         * @brief Construct a new QMC5883P object
         * 
         * @param hi2c Pointer to I2C handle
         * @param mode Operation mode
         * @param spd Output data rate (default: 200Hz)
         * @param rng Measurement range (default: ±2G)
         */
        QMC5883P(I2C_HandleTypeDef *hi2c, QMC5883P_Mode mode, QMC5883P_Spd spd = QMC5883P_Spd::ODR_200HZ,
                 QMC5883P_Rng rng = QMC5883P_Rng::RNG_2G);
        
        /**
         * @brief Destroy the QMC5883P object
         */
        ~QMC5883P();

        /**
         * @brief Initialize the QMC5883P sensor
         * 
         * @return QMC5883P_Status Status of initialization
         */
        QMC5883P_Status begin();

        /**
         * @brief Read new data from the sensor
         * 
         * @return QMC5883P_Status Status of data reading
         */
        QMC5883P_Status update();
        
        /**
         * @brief Get the X-axis magnetic field value
         * 
         * @return float X-axis magnetic field in Gauss
         */
        inline float getX() { return _mag_x; }
        
        /**
         * @brief Get the Y-axis magnetic field value
         * 
         * @return float Y-axis magnetic field in Gauss
         */
        inline float getY() { return _mag_y; }
        
        /**
         * @brief Get the Z-axis magnetic field value
         * 
         * @return float Z-axis magnetic field in Gauss
         */
        inline float getZ() { return _mag_z; }

    private:
        /**
         * @brief Send data to the sensor via I2C
         * 
         * @param reg Register address
         * @param data Pointer to data buffer
         * @param len Length of data
         * @return HAL_StatusTypeDef Status of I2C operation
         */
        HAL_StatusTypeDef _i2cSend(uint8_t reg, uint8_t *data, uint8_t len);
        
        /**
         * @brief Receive data from the sensor via I2C
         * 
         * @param reg Register address
         * @param data Pointer to data buffer
         * @param len Length of data
         * @return HAL_StatusTypeDef Status of I2C operation
         */
        HAL_StatusTypeDef _i2cRecv(uint8_t reg, uint8_t *data, uint8_t len);

        /**
         * @brief Check if new data is available
         * 
         * @return true Data is ready
         * @return false Data is not ready
         */
        bool _isDataRdy();

        I2C_HandleTypeDef *_hi2c;      ///< I2C handle
        QMC5883P_Mode _mode;           ///< Operation mode
        QMC5883P_Spd _speed;           ///< Output data rate
        QMC5883P_Rng _range;           ///< Measurement range
        uint16_t _sensitivity;         ///< Sensitivity based on range

        float _mag_x, _mag_y, _mag_z;  ///< Calibrated magnetic field values

};
